# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: SeleniumWebDriver Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run UI Tests for Project 1
      run: dotnet test TestProject1/TestProject1.csproj
    - name: Run UI Tests for Project 2
      run: dotnet test TestProject2/TestProject1.csproj
    - name: Run UI Tests for Project 3
      run: dotnet test TestProject3/TestProject1.csproj
    
